/* Garden Wonder — the story importer.

   Reads docs/57-volume-one-script.md and writes DATA.story.script into
   data.js, between the two STORY SCRIPT markers. Doc 57's "How to read this
   file" section is the contract; this is its only reader.

     node tools/story-import.js           parse, write data.js, print a summary
     node tools/story-import.js --check   parse and compare, write nothing;
                                          exits 1 if data.js is stale

   It REFUSES rather than guesses. A fenced chunk, table row or list item it
   does not understand stops the run with the doc's line number and writes
   nothing, because a line the engine silently dropped is a line the writer's
   pass will never know went missing. Prose between chunks is ignored on
   purpose — that is where the doc talks to its human reader.

   The one thing it invents is the PROVISIONAL level of each memory sliver and
   story line: doc 57 gives only a window ("ch2–ch3"), and "the spec places
   them". Until it does, they are spread evenly across their window's levels,
   deterministically, so the same doc always writes the same data. */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DOC = path.join(ROOT, 'docs', '57-volume-one-script.md');
const DATA_FILE = path.join(ROOT, 'data.js');
const BEGIN = '/* ==== STORY SCRIPT — generated by tools/story-import.js from docs/57. Edit the doc and re-run; never edit this block by hand. ==== */';
const END = '/* ==== END STORY SCRIPT ==== */';

const SPEAKERS = {
  MARA: 'mara', POPPY: 'poppy', HOLLY: 'holly', DELPHINE: 'delphine', THEO: 'theo', JULIAN: 'julian',
  ISOLDE: 'isolde', BRAM: 'bram', MARIGOLD: 'marigold', HOLLIS: 'hollis', WREN: 'wren', NOTE: 'note'
};
const MOODS = ['neutral', 'happy', 'laugh', 'soft', 'sad', 'worried', 'cross', 'surprised', 'sly', 'dry',
  'tired', 'curious', 'sleepy', 'proud'];
const POPPY_ONLY = ['sleepy', 'proud'];
const MODES = ['think', 'bubble', 'chip', 'strip'];
const RUN_KINDS = ['open', 'hum', 'teach', 'ask', 'turnask', 'after'];
const TEACH_STEPS = ['tap', 'plant', 'harvest', 'upgrade'];
const NAME_TO_ID = {
  delphine: 'delphine', theo: 'theo', julian: 'julian', isolde: 'isolde', wren: 'wren',
  bram: 'bram', 'miss marigold': 'marigold', 'old hollis': 'hollis'
};
/* The one parenthetical a villager's pool heading may carry, and what it means.
   Anything else is refused rather than read as decoration. */
const POOL_NOTES = { 'before the prize': { until: 'ch8' } };
const HERO_TAG = /\[(FALL|SPRING) HERO\]/;

const src = fs.readFileSync(DOC, 'utf8').split('\n');

function refuse(lineNo, why, text) {
  console.error(`story-import: REFUSED at docs/57 line ${lineNo}: ${why}`);
  if (text !== undefined) console.error(`  > ${text}`);
  process.exit(2);
}

const out = {
  chapters: [],
  slivers: [],
  lines: [],
  villagers: {},
  welcome: {},
  flowerLines: [],
  turnLines: {},
  holly: [],
  pending: []
};

/* ---------- a spoken line ---------- */
const LINE_RE = /^([A-Z]+)(?: \((think|bubble|chip|strip)\))?(?: \[([a-z]+)\])?: (.*)$/;
const STRIP_RE = /^\((strip)\): (.*)$/;

function parseLine(raw, lineNo) {
  const t = raw.trim();
  const strip = t.match(STRIP_RE);
  if (strip) return { mode: 'strip', text: strip[2].trim() };
  const m = t.match(LINE_RE);
  if (!m) refuse(lineNo, 'not a line the format knows', raw);
  const who = SPEAKERS[m[1]];
  if (!who) refuse(lineNo, `unknown speaker ${m[1]}`, raw);
  const mode = m[2] || (who === 'note' ? 'note' : 'say');
  const mood = m[3] || null;
  if (mood && !MOODS.includes(mood)) refuse(lineNo, `unknown expression [${mood}]`, raw);
  if (mood && POPPY_ONLY.includes(mood) && who !== 'poppy') refuse(lineNo, `[${mood}] is Poppy's alone`, raw);
  if (who !== 'note' && mode !== 'chip' && !mood) refuse(lineNo, 'a spoken line needs an [expression]', raw);
  if (mode === 'think' && who !== 'mara') refuse(lineNo, 'only Mara has a thought cloud', raw);
  if (mode === 'chip' && who !== 'mara') refuse(lineNo, 'only Mara has reply chips', raw);
  if (mode === 'bubble' && who !== 'poppy') refuse(lineNo, 'only Poppy speaks in the garden bubble', raw);
  let text = m[4].trim();
  const line = { who, mode };
  if (mood) line.mood = mood;
  const met = text.match(/\s*`\?met:([a-z]+)`\s*$/) || text.match(/\s*\?met:([a-z]+)\s*$/);
  if (met) { line.met = met[1]; text = text.slice(0, met.index).trim(); }
  if (mode === 'chip') {
    line.chips = text.split(' | ').map((c) => c.trim()).filter(Boolean);
    if (!line.chips.length || line.chips.length > 2) refuse(lineNo, 'a reply is one or two chips', raw);
    line.text = line.chips[0];
  } else {
    line.text = text;
  }
  if (!line.text) refuse(lineNo, 'an empty line', raw);
  return line;
}

/* ---------- fenced chunks ---------- */
let section = '';        // the nearest ## heading, lower-cased
let chunkHead = null;    // { chapter, kind } from a `### chN.kind` markdown heading
let chapter = null;      // the chapter being filled
let scene = null;        // the scene being filled
let pendingCard = null;  // an @card waiting for the next scene
let run = null;          // the run array being filled
let teachStep = null;
let teachOf = null;      // the chapter whose teach chunk is open

function chapterById(id) { return out.chapters.find((c) => c.id === id); }
function closeChapter() {
  if (pendingCard && scene) { scene.endCard = pendingCard; }
  pendingCard = null;
  scene = null;
}

function startRun(chId, kind, lineNo) {
  const ch = chapterById(chId);
  if (!ch) refuse(lineNo, `a ${kind} chunk for ${chId}, which has no chapter header yet`);
  if (!RUN_KINDS.includes(kind)) refuse(lineNo, `unknown chunk kind .${kind}`);
  ch.runs = ch.runs || {};
  if (ch.runs[kind]) refuse(lineNo, `a second ${chId}.${kind} chunk`);
  if (kind === 'teach') { ch.runs.teach = { intro: [] }; run = ch.runs.teach.intro; teachStep = 'intro'; teachOf = ch; }
  else { ch.runs[kind] = []; run = ch.runs[kind]; teachStep = null; }
  scene = null;
}

function parseChangeList(value, lineNo) {
  return value.split(' · ').map((part) => {
    const p = part.trim();
    const m = p.match(/^([a-z-]+):\s*(.+)$/i);
    if (!m) refuse(lineNo, 'an @change item is key:value', p);
    const item = { kind: m[1] };
    const v = m[2].trim().match(/^([^\s(]+)\s*(?:\((.*)\))?$/);
    if (v) { item.value = v[1]; if (v[2]) item.note = v[2]; } else item.value = m[2].trim();
    if (item.kind === 'order') {
      const om = item.value.match(/^([a-z]+)-([a-z]+)$/);
      if (!om) refuse(lineNo, 'order:<villager>-<good or entry>', p);
      item.villager = om[1];
      item.good = om[2] === 'entry' ? null : om[2];
    }
    if (item.kind === 'counter') item.value = Number(item.value);
    return item;
  });
}

function fenceLine(raw, lineNo) {
  const t = raw.trim();
  if (!t) return;
  // A chapter header.
  let m = t.match(/^### (ch\d+) — (.+?)\s*(?:←.*)?$/);
  if (m) {
    closeChapter();
    if (chapterById(m[1])) refuse(lineNo, `chapter ${m[1]} declared twice`);
    chapter = { id: m[1], n: Number(m[1].slice(2)), title: m[2].trim(), level: null, teaser: '', change: [], notes: [], scenes: [] };
    out.chapters.push(chapter);
    run = null;
    return;
  }
  // A scene header, or an in-fence run header.
  m = t.match(/^#### (ch\d+)\.([a-z0-9]+)(?: · (.*))?$/);
  if (m) {
    const [, chId, kind, rest] = m;
    if (/^s\d+$/.test(kind)) {
      const ch = chapterById(chId);
      if (!ch) refuse(lineNo, `scene ${chId}.${kind} before its chapter header`);
      chapter = ch;
      const sc = { id: `${chId}.${kind}`, room: null, faces: [], lines: [] };
      (rest || '').split(' · ').forEach((part) => {
        const kv = part.match(/^(room|faces): (.*)$/);
        if (!kv) refuse(lineNo, 'a scene header carries room: and faces:', t);
        if (kv[1] === 'room') {
          sc.room = kv[2].split(/[\s(]/)[0];
          if (!['garden', 'meadow', 'stand'].includes(sc.room)) refuse(lineNo, `unknown room ${sc.room}`, t);
          const note = kv[2].match(/\((.*)\)/);
          if (note) sc.roomNote = note[1];
        } else {
          sc.faces = kv[2].split(',').map((f) => f.trim());
          sc.faces.forEach((f) => { if (!Object.values(SPEAKERS).includes(f)) refuse(lineNo, `unknown face ${f}`, t); });
        }
      });
      if (!sc.room || sc.faces.length !== 2 || sc.faces[0] !== 'mara') refuse(lineNo, 'a scene is a room and two faces, Mara first', t);
      if (pendingCard) { sc.card = pendingCard; pendingCard = null; }
      ch.scenes.push(sc);
      scene = sc;
      run = null;
      return;
    }
    closeChapter();
    startRun(chId, kind, lineNo);
    return;
  }
  // Chapter tags.
  m = t.match(/^@([a-z-]+)\s+(.*)$/);
  if (m) {
    const [, tag, value] = m;
    if (tag === 'card') {
      if (scene && !scene.lines.length && !scene.card) scene.card = value.trim();
      else pendingCard = value.trim();
      return;
    }
    if (!chapter) refuse(lineNo, `@${tag} outside a chapter`, t);
    if (tag === 'level') {
      const lv = value.match(/~?(\d+)/);
      if (!lv) refuse(lineNo, '@level needs a number', t);
      chapter.level = Number(lv[1]);
      if (/first Turn/.test(value)) chapter.latch = 'turn';
      return;
    }
    if (tag === 'teaser') { chapter.teaser = value.trim(); return; }
    if (tag === 'change') { chapter.change.push(...parseChangeList(value, lineNo)); return; }
    if (tag === 'change-if-built') { chapter.change.push(...parseChangeList(value, lineNo).map((c) => Object.assign(c, { ifBuilt: true }))); return; }
    if (tag === 'note') { chapter.notes.push(value.trim()); return; }
    refuse(lineNo, `unknown tag @${tag}`, t);
  }
  // A stage direction, and its continuation.
  if (/^— /.test(t) || /^—$/.test(t)) {
    const target = scene ? scene.lines : run;
    if (!target) refuse(lineNo, 'a stage direction outside a scene or run', t);
    target.push({ mode: 'stage', text: t.replace(/^—\s*/, '').replace(/\s*—$/, '') });
    return;
  }
  if (/^\s{3,}\S/.test(raw) && !/^\s*step:/.test(raw) && !/^[A-Z(]/.test(t)) {
    const target = scene ? scene.lines : run;
    const last = target && target[target.length - 1];
    if (!last || last.mode !== 'stage') refuse(lineNo, 'an indented line that continues nothing', t);
    last.text = (last.text + ' ' + t.replace(/\s*—$/, '')).trim();
    return;
  }
  // A teach step.
  m = raw.match(/^\s+step:([a-z]+)\s+(.*)$/);
  if (m) {
    if (teachStep === null) refuse(lineNo, 'a step: line outside the teach chunk', t);
    if (!TEACH_STEPS.includes(m[1])) refuse(lineNo, `unknown teach step ${m[1]}`, t);
    if (teachOf.runs.teach[m[1]]) refuse(lineNo, `a second step:${m[1]}`, t);
    teachOf.runs.teach[m[1]] = [parseLine(m[2], lineNo)];
    return;
  }
  // A spoken line.
  const line = parseLine(raw, lineNo);
  if (HERO_TAG.test(line.text)) { out.pending.push(`${(scene && scene.id) || 'run'}: ${line.text}`); return; }
  if (scene) {
    if (line.mode === 'bubble' || line.mode === 'strip') refuse(lineNo, `a (${line.mode}) line inside a scene`, t);
    scene.lines.push(line);
    return;
  }
  if (run) { run.push(line); return; }
  refuse(lineNo, 'a line with nowhere to go', t);
}

/* ---------- list and table sections ---------- */
function splitItems(s) {
  return s.split(' · ').map((x) => x.trim()).filter(Boolean);
}
function stripShipped(items) {
  return items.filter((x) => !/\*\(shipped\)\*\s*$/.test(x)).map((x) => x.replace(/\s*\*\(shipped\)\*\s*$/, ''));
}

/* Levels the doc never gives: spread evenly across the window, deterministically. */
function levelOf(chId) {
  const ch = chapterById(chId);
  if (!ch || ch.level == null) throw new Error(`no level for ${chId}`);
  return ch.level;
}
function spread(items, fromCh, toCh, afterSpan) {
  const lo = levelOf(fromCh);
  const hi = toCh ? levelOf(toCh) : lo + afterSpan;
  const first = lo + 1;
  const room = Math.max(1, hi - first);
  items.forEach((it, i) => { it.level = Math.min(hi - 1, first + Math.floor((i * room) / items.length)); });
}

let villager = null;   // the new villager section being filled
let linesWindow = null;
const sliverRows = [];
const lineGroups = [];

let inFence = false;
let fenceStart = 0;
for (let i = 0; i < src.length; i += 1) {
  const raw = src[i];
  const lineNo = i + 1;
  if (/^```/.test(raw)) {
    inFence = !inFence;
    if (inFence) fenceStart = lineNo;
    else if (chunkHead === null && chapter === null && !/how to read/.test(section)) {
      /* a fence with nothing to belong to was refused on its first line */
    }
    if (!inFence && section.startsWith('how to read')) continue;
    continue;
  }
  if (inFence) {
    if (section.startsWith('how to read')) continue;
    // A fence under a `### chN.kind` heading starts that run unless it opens with its own header.
    if (lineNo === fenceStart + 1 && chunkHead) {
      if (!/^\s*#{3,4} ch/.test(raw)) startRun(chunkHead.chapter, chunkHead.kind, lineNo);
      chunkHead = null;
    }
    fenceLine(raw, lineNo);
    continue;
  }
  let m = raw.match(/^## (.*)$/);
  if (m) { section = m[1].toLowerCase(); chunkHead = null; villager = null; linesWindow = null; continue; }
  m = raw.match(/^### (ch\d+)\.([a-z]+) — /);
  if (m) { chunkHead = { chapter: m[1], kind: m[2] }; continue; }
  if (/^### /.test(raw)) {
    chunkHead = null;
    const vm = raw.match(/^### (\w+) — arrives at (ch\d+)$/);
    if (section === 'the villagers' && vm) {
      const id = vm[1].toLowerCase();
      villager = out.villagers[id] = { arrives: vm[2], greet: [], waiting: [], delivered: [], after: {} };
      continue;
    }
    villager = null;
    if (section === 'the villagers' && /^### (Isolde, the Baroness) — arrives at (ch\d+)$/.test(raw)) {
      const im = raw.match(/arrives at (ch\d+)/);
      villager = out.villagers.isolde = { arrives: im[1], greet: [], waiting: [], delivered: [], after: {} };
    }
    continue;
  }

  if (section.startsWith('between chapters — memory slivers')) {
    const row = raw.match(/^\| (m\d+) \| ([^|]+) \| (.+) \|$/);
    if (row) {
      const win = row[2].trim();
      let from; let to;
      const a = win.match(/^after (ch\d+)$/);
      const b = win.match(/^(ch\d+)–(ch\d+)$/);
      if (a) { from = a[1]; to = null; } else if (b) { from = b[1]; to = b[2]; } else refuse(lineNo, 'a sliver window is "after chN" or "chA–chB"', raw);
      let text = row[3].trim();
      const note = text.match(/\s*\*\((.*)\)\*\s*$/);
      if (note) {
        if (HERO_TAG.test(note[1])) out.pending.push(`${row[1]}: ${note[1]}`);
        text = text.slice(0, note.index).trim();
      }
      if (HERO_TAG.test(text)) { out.pending.push(`${row[1]}: ${text}`); continue; }
      sliverRows.push({ id: row[1], from, to, text });
      continue;
    }
    if (/^\|/.test(raw) && !/^\| (id|---)/.test(raw)) refuse(lineNo, 'a sliver row the table does not understand', raw);
    continue;
  }

  if (section.startsWith('between chapters — story lines')) {
    const head = raw.match(/^\*\*(ch\d+) → (ch\d+)\*\*$/) || raw.match(/^\*\*after (ch\d+) — .*\*\*$/);
    if (head) {
      linesWindow = { from: head[1], to: head[2] || null, items: [] };
      lineGroups.push(linesWindow);
      continue;
    }
    const b = raw.match(/^- (.*)$/);
    if (b) {
      if (!linesWindow) refuse(lineNo, 'a story line before its window heading', raw);
      let text = b[1].trim();
      const item = {};
      const met = text.match(/\s*`\?met:([a-z]+)`\s*$/);
      if (met) { item.met = met[1]; text = text.slice(0, met.index).trim(); }
      if (HERO_TAG.test(text)) { out.pending.push(`line: ${text}`); continue; }
      item.text = text;
      linesWindow.items.push(item);
    }
    continue;
  }

  if (section === 'the villagers') {
    const b = raw.match(/^- \*\*([^*]+):\*\* (.*)$/);
    if (villager && b) {
      const key = b[1].trim();
      const items = splitItems(b[2]);
      if (['greet', 'waiting', 'delivered'].includes(key)) { villager[key].push(...items); continue; }
      const am = key.match(/^after (ch\d+)(?: \((.*)\))?$/);
      if (am) {
        const entry = { lines: items };
        if (am[2]) {
          const rule = POOL_NOTES[am[2].toLowerCase()];
          if (!rule) refuse(lineNo, `unknown pool note (${am[2]})`, raw);
          Object.assign(entry, rule);
        }
        villager.after[am[1]] = entry;
        continue;
      }
      refuse(lineNo, `unknown pool ${key}`, raw);
    }
    // Existing villagers: "- **Bram, after ch4:** …" or Wren's mixed line.
    const ex = raw.match(/^- \*\*([A-Z][a-z]+(?: [A-Z][a-z]+)?), after (ch\d+):\*\* (.*)$/);
    if (ex) {
      const id = NAME_TO_ID[ex[1].toLowerCase()];
      if (!id) refuse(lineNo, `unknown villager ${ex[1]}`, raw);
      const v = out.villagers[id] = out.villagers[id] || { greet: [], waiting: [], delivered: [], after: {} };
      v.after[ex[2]] = { lines: splitItems(ex[3]) };
      continue;
    }
    const wm = raw.match(/^- \*\*(Wren)\*\* \([^)]*\): (.*)$/);
    if (wm) {
      const v = out.villagers.wren = out.villagers.wren || { greet: [], waiting: [], delivered: [], after: {} };
      const parts = wm[2].split(/\*\*([a-z0-9 ]+):\*\*/).map((x) => x.trim());
      for (let k = 1; k < parts.length; k += 2) {
        const key = parts[k];
        const items = stripShipped(splitItems(parts[k + 1] || ''));
        if (['greet', 'waiting', 'delivered'].includes(key)) v[key].push(...items);
        else if (/^after ch\d+$/.test(key)) v.after[key.slice(6)] = { lines: items };
        else refuse(lineNo, `unknown pool ${key}`, raw);
      }
      continue;
    }
    if (/^- /.test(raw)) refuse(lineNo, 'a villager line the format does not know', raw);
    continue;
  }

  if (section.startsWith('the welcome-back board')) {
    const b = raw.match(/^- \*\*([A-Za-z]+):\*\* (.*)$/);
    if (b) {
      const id = NAME_TO_ID[b[1].toLowerCase()];
      if (!id) refuse(lineNo, `unknown villager ${b[1]}`, raw);
      out.welcome[id] = splitItems(b[2]);
      continue;
    }
    if (/^- /.test(raw)) refuse(lineNo, 'a welcome line the format does not know', raw);
    continue;
  }

  if (section.startsWith("poppy's voice")) {
    const row = raw.match(/^\| ([a-z]+) \| ([^|]+) \| ([^|]+) \|$/);
    if (row && row[1] !== 'bucket') { out.flowerLines.push({ bucket: row[1], from: row[2].trim(), to: row[3].trim() }); continue; }
    const tl = raw.match(/^- (toddler|child|wry): (.*)$/);
    if (tl) { out.turnLines[tl[1]] = tl[2].trim(); continue; }
    if (/^- /.test(raw)) refuse(lineNo, 'a Turn line the format does not know', raw);
    continue;
  }

  if (section.startsWith('holly')) {
    const row = raw.match(/^\| ([^|]+) \| ([^|]+) \|$/);
    if (row && !/^(Shipped|---)/.test(row[1].trim())) { out.holly.push({ from: row[1].trim(), to: row[2].trim() }); continue; }
    continue;
  }
}
if (inFence) refuse(src.length, 'the file ends inside a fence');
closeChapter();

/* ---------- checks the format promises ---------- */
out.chapters.forEach((ch) => {
  if (ch.level == null) refuse(0, `${ch.id} has no @level`);
  if (!ch.title) refuse(0, `${ch.id} has no title`);
  ch.scenes.forEach((sc) => {
    if (!sc.lines.some((l) => l.mode !== 'stage')) refuse(0, `${sc.id} has no lines`);
    sc.lines.forEach((l) => {
      if (l.who && l.who !== 'note' && l.who !== 'poppy' && !sc.faces.includes(l.who)) {
        refuse(0, `${sc.id}: ${l.who} speaks but is not one of the scene's faces`);
      }
    });
  });
  const vill = ch.change.filter((c) => c.kind === 'villager').map((c) => c.value);
  vill.forEach((v) => {
    if (!out.villagers[v] || out.villagers[v].arrives !== ch.id) refuse(0, `${ch.id} says villager:${v} but the villagers section disagrees`);
  });
});
Object.entries(out.villagers).forEach(([id, v]) => {
  if (v.arrives && !chapterById(v.arrives)) refuse(0, `${id} arrives at ${v.arrives}, which does not exist`);
  if (v.arrives && !['greet', 'waiting', 'delivered'].every((k) => v[k].length)) refuse(0, `${id} arrives with an empty pool`);
});
const order = out.chapters.map((c) => c.n);
if (order.some((n, i) => n !== i + 1)) refuse(0, 'chapters are not ch1..chN in order');
if (!chapterById('ch1').runs || !['open', 'hum', 'teach', 'ask'].every((k) => chapterById('ch1').runs[k])) {
  refuse(0, 'Chapter I needs its open, hum, teach and ask runs');
}

/* ---------- levels for the between-chapter kinds ---------- */
const AFTER_SPAN = 10;
{
  const groups = {};
  sliverRows.forEach((r) => { const k = `${r.from}|${r.to}`; (groups[k] = groups[k] || []).push(r); });
  Object.values(groups).forEach((g) => {
    if (g[0].to === null) g.forEach((r) => { r.level = levelOf(r.from); });
    else spread(g, g[0].from, g[0].to, AFTER_SPAN);
  });
  const ids = sliverRows.map((r) => r.id);
  if (ids.some((id, i) => id !== `m${String(i + 1).padStart(2, '0')}`)) refuse(0, 'slivers are not m01..mNN in order');
  out.slivers = sliverRows.map((r) => ({ id: r.id, from: r.from, level: r.level, text: r.text }));
}
{
  let n = 0;
  lineGroups.forEach((g) => {
    spread(g.items, g.from, g.to, AFTER_SPAN);
    g.items.forEach((it) => {
      n += 1;
      const row = { id: `l${String(n).padStart(3, '0')}`, from: g.from, level: it.level, text: it.text };
      if (it.met) row.met = it.met;
      out.lines.push(row);
    });
  });
}

/* ---------- write ---------- */
function lit(v, ind) {
  const pad = '  '.repeat(ind);
  const padIn = '  '.repeat(ind + 1);
  if (v === null) return 'null';
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) {
    if (!v.length) return '[]';
    const flat = v.every((x) => typeof x !== 'object' || x === null);
    const parts = v.map((x) => lit(x, ind + 1));
    const one = `[${parts.join(', ')}]`;
    if (flat && one.length + pad.length < 110) return one;
    if (v.every((x) => x && typeof x === 'object' && !Array.isArray(x))) {
      const inline = v.map((x) => lit(x, ind + 1));
      if (inline.every((s) => !s.includes('\n') && s.length + padIn.length < 150)) return `[\n${inline.map((s) => padIn + s).join(',\n')}\n${pad}]`;
    }
    return `[\n${parts.map((s) => padIn + s).join(',\n')}\n${pad}]`;
  }
  const keys = Object.keys(v).filter((k) => v[k] !== undefined);
  if (!keys.length) return '{}';
  const key = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : `'${k}'`);
  const parts = keys.map((k) => `${key(k)}: ${lit(v[k], ind + 1)}`);
  const one = `{ ${parts.join(', ')} }`;
  if (!one.includes('\n') && one.length + pad.length < 150) return one;
  return `{\n${parts.map((s) => padIn + s).join(',\n')}\n${pad}}`;
}

const block = `${BEGIN}\nDATA.story.script = ${lit(out, 0)};\n${END}`;
const data = fs.readFileSync(DATA_FILE, 'utf8');
const a = data.indexOf(BEGIN);
const b = data.indexOf(END);
if (a < 0 || b < 0 || b < a) { console.error('story-import: data.js has no STORY SCRIPT markers'); process.exit(2); }
const next = data.slice(0, a) + block + data.slice(b + END.length);

const words = (s) => (s ? s.split(/\s+/).filter(Boolean).length : 0);
let total = 0;
out.chapters.forEach((ch) => {
  ch.scenes.forEach((sc) => sc.lines.forEach((l) => { if (l.mode !== 'stage') total += words(l.chips ? l.chips.join(' ') : l.text); }));
  Object.values(ch.runs || {}).forEach((r) => (Array.isArray(r) ? r : Object.values(r).flat())
    .forEach((l) => { if (l.mode !== 'stage') total += words(l.chips ? l.chips.join(' ') : l.text); }));
});
out.slivers.forEach((s) => { total += words(s.text); });
out.lines.forEach((s) => { total += words(s.text); });

if (process.argv.includes('--check')) {
  if (next !== data) { console.error('story-import: data.js is STALE against docs/57 — run node tools/story-import.js'); process.exit(1); }
  console.log('story-import: data.js matches docs/57.');
  process.exit(0);
}
fs.writeFileSync(DATA_FILE, next);
console.log(`story-import: ${out.chapters.length} chapters, ${out.chapters.reduce((n, c) => n + c.scenes.length, 0)} scenes, `
  + `${out.slivers.length} slivers, ${out.lines.length} story lines, ${Object.keys(out.villagers).length} villagers' pools, `
  + `~${total} words in chapters, slivers and lines.`);
if (out.pending.length) console.log(`pending (hero beats skipped, never rendered):\n  ${out.pending.join('\n  ')}`);
